# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0ffc27cf5db4cf18bb625bd040cedb3c39109fffd4387f8ffbb56f39d5f61e70cc96efff4216aa53e4b6b97d4f3210c14669b6bf7bd6eda538f8faa706ce201d

test:
  secret_key_base: 83b3bf6e12774fec3ef54e73de5fc9a0417fd71277e233b2c8183a8449b1a98cb77011befeb342b442df82c5322803290b2bc7ab67126efaec0d7572f796b628

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
